bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/models/bet.py
from lib.util_sqlalchemy import ResourceMixin
from lib.util_datetime import tzware_datetime
from snakeeyes.extensions import db


class Bet(ResourceMixin, db.Model):
    __tablename__ = 'bets'
    id = db.Column(db.Integer, primary_key=True)

    # Relationships.
    user_id = db.Column(db.Integer, db.ForeignKey('users.id',
                                                  onupdate='CASCADE',
                                                  ondelete='CASCADE'),
                        index=True, nullable=False)

    # Bet details.
    guess = db.Column(db.Integer())
    die_1 = db.Column(db.Integer())
    die_2 = db.Column(db.Integer())
    roll = db.Column(db.Integer())
    wagered = db.Column(db.BigInteger())
    payout = db.Column(db.Float())
    net = db.Column(db.BigInteger())

    def __init__(self, **kwargs):
        # Call Flask-SQLAlchemy's constructor.
        super(Bet, self).__init__(**kwargs)

    @classmethod
    def is_winner(cls, guess, roll):
        """
        Determine if the result is a win or loss.

        :param guess: Dice guess
        :type guess: int
        :param roll: Dice roll
        :type roll: int
        :return: bool
        """
        if guess == roll:
            return True

        return False

    @classmethod
    def determine_payout(cls, payout, is_winner):
        """
        Determine the payout.

        :param payout: Dice guess
        :type payout: float
        :param is_winner: Was the bet won or lost
        :type is_winner: bool
        :return: int
        """
        if is_winner:
            return payout

        return 1.0

    @classmethod
    def calculate_net(cls, wagered, payout, is_winner):
        """
        Calculate the net won or lost.

        :param wagered: Dice guess
        :type wagered: int
        :param payout: Dice roll
        :type payout: float
        :param is_winner: Was the bet won or lost
        :type is_winner: bool
        :return: int
        """
        if is_winner:
            return int(wagered * payout)

        return -wagered

    def save_and_update_user(self, user):
        """
        Commit the bet and update the user's information.

        :return: SQLAlchemy save result
        """
        self.save()

        user.coins += self.net
        user.last_bet_on = tzware_datetime()
        return user.save()

    def to_json(self):
        """
        Return JSON fields to represent a bet.

        :return: dict
        """
        params = {
          'guess': self.guess,
          'die_1': self.die_1,
          'die_2': self.die_2,
          'roll': self.roll,
          'wagered': self.wagered,
          'payout': self.payout,
          'net': self.net,
          'is_winner': Bet.is_winner(self.guess, self.roll)
        }

        return params

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/models/coin.py
def add_subscription_coins(coins, previous_plan, plan, cancelled_on):
    """
    Add an amount of coins to an existing coin value.

    :param coins: Existing coin value
    :type coins: int
    :param previous_plan: Previous subscription plan
    :type previous_plan: dict
    :param plan: New subscription plan
    :type plan: dict
    :param cancelled_on: When a plan has potentially been cancelled
    :type cancelled_on: datetime
    :return: int
    """
    # Some people will try to game the system and cheat us for extra coins.
    #
    # Users should only be able to gain coins via subscription when:
    #   Subscribes for the first time
    #   Subscriber updates to a better plan (one with more coins)
    #
    # That means the following actions should result in no coins:
    #   Subscriber cancels and signs up for the same plan
    #   Subscriber downgrades to a worse plan
    #
    # This method is still cheatable by signing up for a free trial on a plan,
    # and then upgrading to a higher plan. However, only a small amount of
    # users will do this, and once their subscription runs out they will be
    # removed from the leaderboard.
    #
    # I feel like it's better to allow them to temporarily cheat the system
    # instead of adding subscription coins during the invoicing phase which
    # will mean that honest people who subscribe won't be able to get their
    # coins until after the free trial period.
    previous_plan_coins = 0
    plan_coins = plan['metadata']['coins']

    if previous_plan:
        previous_plan_coins = previous_plan['metadata']['coins']

    if cancelled_on is None and plan_coins == previous_plan_coins:
        coin_adjustment = plan_coins
    elif plan_coins <= previous_plan_coins:
        return coins
    else:
        # We only want to add the difference between upgrading plans,
        # because they were already credited the previous plan's coins.
        coin_adjustment = plan_coins - previous_plan_coins

    return coins + coin_adjustment

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/models/dice.py
import random


def roll():
    """
    Randomly roll a dice.

    :return: int
    """
    return random.randint(1, 6)

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/forms.py
from flask_wtf import Form
from wtforms import IntegerField
from wtforms.validators import DataRequired, NumberRange


class BetForm(Form):
    guess = IntegerField('Guess', [DataRequired(), NumberRange(min=2, max=12)])
    wagered = IntegerField('Wagered', [DataRequired(), NumberRange(min=1)])

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/__init__.py
from snakeeyes.blueprints.bet.views import bet

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/views.py
from flask import Blueprint, current_app, render_template, request
from flask_login import current_user, login_required

from lib.util_json import render_json
from snakeeyes.extensions import limiter
from snakeeyes.blueprints.bet.decorators import coins_required
from snakeeyes.blueprints.bet.forms import BetForm
from snakeeyes.blueprints.bet.models.bet import Bet
from snakeeyes.blueprints.bet.models.dice import roll

bet = Blueprint('bet', __name__, template_folder='templates',
                url_prefix='/bet')


@bet.before_request
@login_required
def before_request():
    """ Protect all of the bet endpoints. """
    pass


@bet.route('/place', methods=['GET', 'POST'])
@coins_required
@limiter.limit('3/second')
def place_bet():
    if request.method == 'GET':
        recent_bets = Bet.query.filter(Bet.user_id == current_user.id) \
            .order_by(Bet.created_on.desc()).limit(10)

        return render_template('bet/place_bet.html', recent_bets=recent_bets)

    form = BetForm()

    if form.validate_on_submit():
        guess = int(request.form.get('guess'))
        wagered = int(request.form.get('wagered'))

        if wagered > current_user.coins:
            error = 'You cannot wager more than your total coins.'
            return render_json(400, {'error': error})

        payout = float(current_app.config['DICE_ROLL_PAYOUT'][str(guess)])
        die_1 = roll()
        die_2 = roll()
        outcome = die_1 + die_2
        is_winner = Bet.is_winner(guess, outcome)
        payout = Bet.determine_payout(payout, is_winner)
        net = Bet.calculate_net(wagered, payout, is_winner)

        params = {
          'user_id': current_user.id,
          'guess': guess,
          'die_1': die_1,
          'die_2': die_2,
          'roll': outcome,
          'wagered': wagered,
          'payout': payout,
          'net': net
        }

        bet = Bet(**params)
        bet.save_and_update_user(current_user)

        return render_json(200, {'data': bet.to_json()})
    else:
        return render_json(400,
                           {'error': 'You need to wager at least 1 coin.'})


@bet.route('/history', defaults={'page': 1})
@bet.route('/history/page/<int:page>')
def history(page):
    paginated_bets = Bet.query \
        .filter(Bet.user_id == current_user.id) \
        .order_by(Bet.created_on.desc()) \
        .paginate(page, 50, True)

    return render_template('bet/history.html', bets=paginated_bets)

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/templates/bet/history.html
{% extends 'layouts/app.html' %}
{% import 'macros/items.html' as items %}

{% block title %}Betting history{% endblock %}

{% block body %}
  <h2>Betting history</h2>
  {% if bets.total == 0 %}
    <p>No bets found.</p>
  {% else %}
    <table class="table">
      <thead>
      <tr>
        <th>Date</th>
        <th>Guess</th>
        <th>Roll</th>
        <th>Wagered</th>
        <th>Payout</th>
        <th>Net</th>
      </tr>
      </thead>
      <tbody>
      {% for bet in bets.items %}
        <tr>
          <td>
            <time class="from-now"
                  data-datetime="{{ bet.created_on }}">
              {{ bet.created_on }}
            </time>            
          </td>
          <td>{{ bet.guess }}</td>
          <td>
            {{ bet.roll }}
            <span class="text-muted">({{ bet.die_1 }} + {{ bet.die_2 }})</span>
          </td>
          <td class="text-warning">
            <i class="fa fa-fw fa-database"></i> {{ bet.wagered }}
          </td>
          <td>{{ bet.payout }}x</td>
          <td class="text-{{ 'success' if bet.net > 0 else 'danger' }}">
            <i class="fa fa-fw fa-database"></i> {{ bet.net }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    {{ items.paginate(bets) }}
  {% endif %}
  <hr/>
  <a href="{{ url_for('user.settings') }}" class="margin-top btn btn-primary">
    Go back to your account
  </a>
{% endblock %}

bsawf-course-material/20-internationalization-i18n/snakeeyes/blueprints/bet/templates/bet/place_bet.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Place Bet{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4">
      <form id="place_bet" class="sm-margin-top">
        <legend class="text-warning">
          <strong id="user_coins">{{ current_user.coins }}</strong> coins left
        </legend>
        <div class="form-group">
          <label for="guess"><strong>Guess</strong></label>
            <select class="form-control" id="guess" name="guess"
                    title="What number will be rolled?">
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
              <option value="11">11</option>
              <option value="12">12</option>
            </select>
        </div>
        <div class="form-group">
          <label for="wager"><strong>Wager</strong></label>
            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-fw fa-database"></i>
              </div>
              <input type="number" min="1" class="form-control"
                     id="wagered" name="wagered"
                     placeholder="100" title="How many coins do you want to wager?">
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block sm-margin-top">
          <img src="{{ url_for('static', filename='images/spinner.gif') }}"
               class="spinner"
               width="16" height="11" alt="Spinner"/>
          Place Bet
        </button>

        <noscript>
          <p class="alert alert-sm alert-warning text-center sm-margin-top">
            You need to enable JavaScript to place bets.
          </p>
        </noscript>

        <div id="dice" class="text-center"></div>
        <div id="outcome" class="alert alert-sm text-center sm-margin-top"></div>

        <hr/>

        <div class="text-center">
          <a href="{{ url_for('billing.purchase_coins') }}"
             class="btn btn-default">Buy more coins</a>
        </div>
      </form>
    </div>
    <div class="col-md-7 col-md-offset-1">
      <div id="recent_bets">
        <h2>Recent bets</h2>
        {% if recent_bets.count() == 0 %}
          <p>No bets found.</p>
        {% else %}
          <table class="table">
            <thead>
            <tr>
              <th>Guess</th>
              <th>Roll</th>
              <th>Wagered</th>
              <th>Payout</th>
              <th>Net</th>
            </tr>
            </thead>
            <tbody>
            {% for bet in recent_bets %}
              <tr>
                <td>{{ bet.guess }}</td>
                <td>{{ bet.roll }}</td>
                <td class="text-warning">
                  <i class="fa fa-fw fa-database"></i> {{ bet.wagered }}
                </td>
                <td>{{ bet.payout }}x</td>
                <td class="text-{{ 'success' if bet.net > 0 else 'danger' }}">
                  <i class="fa fa-fw fa-database"></i> {{ bet.net }}
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        {% endif %}
        <a href="{{ url_for('bet.history') }}">
          <span class="btn btn-sm btn-default">View full betting history</span>
        </a>
      </div>
    </div>
  </div>
{% endblock %}